Материал для [Youtube курса по NumPy](https://www.youtube.com/playlist?list=PLA0M1Bcd0w8zmegfAUfFMiACPKfdW4ifD) от Сергея Балакирева


In [128]:
import numpy as np

### Основные типы данных. Создание массивов.

In [129]:
# при создании массива можно вторым аргументом указать необходимый тип данных
a = np.array([1, 2, 3], "float64")

In [130]:
a

array([1., 2., 3.])

In [131]:
# все возможные типы данных, которые поддерживает numpy
np.sctypeDict

{'bool': numpy.bool,
 'float16': numpy.float16,
 'float32': numpy.float32,
 'float64': numpy.float64,
 'longdouble': numpy.longdouble,
 'complex64': numpy.complex64,
 'complex128': numpy.complex128,
 'clongdouble': numpy.clongdouble,
 'bytes_': numpy.bytes_,
 'str_': numpy.str_,
 'void': numpy.void,
 'object_': numpy.object_,
 'datetime64': numpy.datetime64,
 'timedelta64': numpy.timedelta64,
 'int8': numpy.int8,
 'byte': numpy.int8,
 'uint8': numpy.uint8,
 'ubyte': numpy.uint8,
 'int16': numpy.int16,
 'short': numpy.int16,
 'uint16': numpy.uint16,
 'ushort': numpy.uint16,
 'int32': numpy.int32,
 'intc': numpy.int32,
 'uint32': numpy.uint32,
 'uintc': numpy.uint32,
 'int64': numpy.int64,
 'long': numpy.int64,
 'uint64': numpy.uint64,
 'ulong': numpy.uint64,
 'longlong': numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'intp': numpy.int64,
 'uintp': numpy.uint64,
 'double': numpy.float64,
 'cdouble': numpy.complex128,
 'single': numpy.float32,
 'csingle': numpy.complex64,
 'half': numpy.

In [132]:
a

array([1., 2., 3.])

In [133]:
# таким образом можно преобразовывать данные / массивы, создаётся копия
print(np.int8(16.999999999))
print(np.int8(a))

16
[1 2 3]


In [134]:
b = np.array([[1, 2], [3, 4], [5, 6]])

In [135]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [136]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [137]:
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [138]:
# к элементам можно обращаться так (равносильно c[1][0][1])
c[1, 0, 1]

np.int64(6)

In [139]:
c[1, 0, 1] == c[1][0][1]

np.True_

### Функции автозаполнения, создания матриц и числовых диапазонов.

In [140]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [141]:
np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
# np.empty(shape, ...)
# Возвращает новый массив заданного размера и типа данных, но без определённых значений.
np.empty((2, 3))

array([[0.e+000, 1.e-323, 1.e-323],
       [1.e-323, 1.e-323, 1.e-323]])

In [143]:
# np.eye(N, M=None, ...)
# Возвращает массив размером N*M с единичными диагональными элементами (остальные равны 0)
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [144]:
# np.identity(n, ...)
# Возвращает квадратный массив с единичными диагональными элементами (остальные равны 0)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [145]:
# np.zeros(shape, ...)
# Возвращает массив заданного размера и типа, состоящего из всех нулей
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [146]:
# np.ones(shape, ...)
# Возвращает массив заданного размера и типа, состоящего из всех единиц
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [147]:
# np.full(shape, value, ...)
# Возвращает массив заданного размера и типа со значениями value.
np.full((2, 3), 11)

array([[11, 11, 11],
       [11, 11, 11]])

In [148]:
# np.asmatrix("str")
# создаёт матрицу из строки
np.asmatrix("1 2 3 4")
# np.asmatrix("1 2 3 4") == np.asmatrix("1, 2, 3, 4")

matrix([[1, 2, 3, 4]])

In [149]:
# через ; можно создавать двумерную матрицу
np.asmatrix("1 2 3; 4 5 6")
# np.asmatrix("1 2 3; 4 5 6") == np.mat([(1, 2, 3), (4, 5, 6)])
# np.asmatrix("1 2 3; 4 5 6") == np.asmatrix([(1, 2, 3), (4, 5, 6)])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [150]:
# np.diag([a, b, c])
# создает матрицу, где на главной диагонали будут элементы a, b, c
np.diag([1, 2, 5])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 5]])

In [151]:
# Если в np.diag передать двумерный список или массив
# то эта функция выделяет элементы, стоящие на главной диагонали
np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([1, 5, 9])

In [152]:
# np.tri(shape)
# создаёт матрицу размером shape где все элементы на главной диагонали и под ней - единицы
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [153]:
np.tri(4, 2)

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [154]:
# Если в np.tril передать массив, то обнулятся все элементы над главной диагональю
a = np.arange(9).reshape(3, 3)

In [155]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [156]:
np.tril(a)

array([[0, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [157]:
# Обратно работает np.triu
np.triu(np.arange(9).reshape(3, 3))

array([[0, 1, 2],
       [0, 4, 5],
       [0, 0, 8]])

Название | Описание
--- | ---
arange() | Возвращает одномерный массив с равномерно разнесёнными числами указанного диапазаона.
linspace(start, stop, ...) | Возвращает одномерный массив с равномерно разнесёнными числами, используя только значения начала и конца интервала.
logspace(start, stop, ...) | Возвращает одномерный массив с числами, равномерно распределённых по логарифмической шкале.
geomspace(start, stop, ...) | Формирование чисел по геометрической прогрессии.
meshgrid(x1, ..., xn, ...) | x1, ..., xn - одномерные последовательности или массивы, используемые для формирования координатной сетки по каждой из осей.
mgrid[] | Возвращает массив плотных координатных сеток.
ogrid[] | Возвращает открытую сетку значений.

In [158]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [159]:
# Можно указывать вещественные значения и константы
np.arange(1, 5, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [160]:
# np.linspace
# при указании в качестве количества значений
# 1 - получим только начало диапазона
# 2 - начало и конец
# 3 - начало, конец и среднее арифметическое
# и т. д.
for i in range(1, 5):
    print(np.linspace(0, np.pi, i))

[0.]
[0.         3.14159265]
[0.         1.57079633 3.14159265]
[0.         1.04719755 2.0943951  3.14159265]


In [161]:
# np.logspace - логарифмическая шкала
for i in range(1, 5):
    print(np.logspace(0, 3, i))


[1.]
[   1. 1000.]
[   1.          31.6227766 1000.       ]
[   1.   10.  100. 1000.]


In [162]:
# np.geomspace геометрическая прогрессия
np.geomspace(1, 16, 5)

array([ 1.,  2.,  4.,  8., 16.])

Фнукции формирования массивов на основе данных
Название | Описание
--- | ---
array(object, ...) | Преобразует список или кортеж object в массив NumPy.
asanyarray(list, ...) | Преобразует список list в массив array, сохраняя тип подкласса.
ascontiguousarray(list, ...) | Возвращает непрерывный массив в памяти, подобно как это организовано в языке C.
asmatrix(list, ...) | Преобразует входную последовательность list в матрицу NumPy (тип matrix).
copy(list, ...) | Возвращает копию массива list (если это объект Numpy) или просто создаёт массив на основе списка языка Python.
frombuffer(buffer, ...) | Преобразует данные из буфера в массив NumPy.
fromfile(file, ...) | Возвращает массив из данных текстового или бинарного файла file.
fromfunction(func, shape, ...) | Создаёт массив размерностью shape с помощью функции func.
fromiter(iter, ...) | Создаёт массив на основе итерируемого объекта.
fromstring(string, ...) | Создаёт массив из данных строки.
loadtxt(file, ...) | Формирует массив из данных текстового файла.

In [163]:
a = np.array([[1, 2], [3, 4]])
b = a

In [164]:
b[0][1] = 100
b

array([[  1, 100],
       [  3,   4]])

In [165]:
a

array([[  1, 100],
       [  3,   4]])

In [166]:
c = np.copy(a)

In [167]:
c[0][1] = - 1000
print(c, a, sep='\n')

[[    1 -1000]
 [    3     4]]
[[  1 100]
 [  3   4]]


### Свойства и представления массивов, создание их копий

In [168]:
a = np.array([.1, .2, .3, .4, .5, .6, .7, .8, .9,])
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [169]:
# количество элементов
a.size

9

In [170]:
# размер одного элемента в байтах
a .itemsize

8

In [171]:
# Общее количество байтов для массива
a.size * a.itemsize

72

In [172]:
b = np.ones((3, 4, 5))

In [173]:
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [174]:
# Количество осей
b.ndim

3

In [175]:
# Форма массива
b.shape

(3, 4, 5)

In [176]:
# Изменение формы массива
b.shape = (12, 5)
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [177]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [178]:
c = b.reshape((2, 2, 15))
c

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [179]:
a = np.array([x for x in range(1, 10)])
b = a.view() # .view() создаёт копию представления
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
a.shape = 3, 3
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [181]:
b # представление b не изменилось в следствие изменение формы массива а

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
a[0][0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [183]:
b # но при внесении изменений в a, массив b также изменился
# но при использовании b = a.copy() или b = np.array(a), создаётся копия массива
# и при внесении изменений в один массив, другой будет оставаться неизменным.

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

### Изменение формы массивов, добавление и удаление осей

In [184]:
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [185]:
# Изменить форму представления так, чтобы стало 3 столбца
a.shape = -1, 3
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [186]:
a.reshape(-1, 1)

array([[100],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [187]:
a.reshape(1, -1)

array([[100,   2,   3,   4,   5,   6,   7,   8,   9]])

In [188]:
# вытягивает массив в вектор
a.ravel()

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [189]:
a = np.arange(1, 16)
a.resize((5, 3))
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [190]:
# reshape создаёт новый массив с новой формой
# resize изменяет исходный массив и не создаёт новый (возвращает None)

In [191]:
x_test = np.arange(32).reshape(8, 2, 2)
x_test

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [192]:
# expand_dims добавляет новые оси, но создаёт новое представление массива
x_test_new = np.expand_dims(x_test, axis=0)
x_test_new.shape

(1, 8, 2, 2)

In [193]:
x_test_new[0, 0, 0, 0] = -100
x_test

array([[[-100,    1],
        [   2,    3]],

       [[   4,    5],
        [   6,    7]],

       [[   8,    9],
        [  10,   11]],

       [[  12,   13],
        [  14,   15]],

       [[  16,   17],
        [  18,   19]],

       [[  20,   21],
        [  22,   23]],

       [[  24,   25],
        [  26,   27]],

       [[  28,   29],
        [  30,   31]]])

In [194]:
a = np.append(x_test_new, x_test_new, axis=0)
a.shape

(2, 8, 2, 2)

In [195]:
# delete удаляет указанный элемент (откуда, индекс, по какой оси)
b = np.delete(a, 0, axis=0)
b.shape

(1, 8, 2, 2)

In [196]:
c = np.delete(a, 0, axis=1)
c.shape

(2, 7, 2, 2)

In [197]:
d = np.expand_dims(x_test_new, axis=-1)
d.shape

(1, 8, 2, 2, 1)

In [198]:
# np.squeeze удаляет все оси, у которых есть только один элемент
e = np.squeeze(d)
e.shape

(8, 2, 2)

In [199]:
# или же можно удалить конкретную ось
e = np.squeeze(d, axis=0)
e.shape

(8, 2, 2, 1)

In [200]:
# при указании оси, в которой более одного элемента, возникнет ошибка
try:
    e = np.squeeze(d, axis=2)
except Exception as e:
    print(f"Exception: {e}.")

Exception: cannot select an axis to squeeze out which has size not equal to one.


In [201]:
a = np.arange(1, 10)
a.shape

(9,)

In [202]:
# newaxis добавляет новую ось
b = a[np.newaxis, :]
b.shape

(1, 9)

In [203]:
b = a[:, np.newaxis]
b.shape

(9, 1)

### Объединение и разделение массивов

#### Объединение массивов

In [315]:
a = np.array([(1, 2), (3, 4)])
b = np.array([(5, 6), (7, 8)])

In [316]:
print(a, b, sep="\n")

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [317]:
# hstack возвращает копию массивов a и b, объединённых по горизонтали.
np.hstack([a, b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [318]:
# hstack возвращает копию массивов a и b, объединённых по вертикали.
np.vstack([a, b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [319]:
a = a.ravel()
b = b.ravel()

In [320]:
print(np.hstack([a, b]))
print(np.vstack([a, b]))
print(np.column_stack([a, b]))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [321]:
a = np.arange(1, 13)
b = np.arange(13, 26)
a.resize(3, 3, 2)
b.resize(3, 3, 2)

In [322]:
c0 = np.concatenate([a, b], axis=0)
c1 = np.concatenate([a, b], axis=1)
c2 = np.concatenate([a, b], axis=2)
print(c0.shape, c1.shape, c2.shape)

(6, 3, 2) (3, 6, 2) (3, 3, 4)


In [323]:
np.r_[[1, 2, 3], 4, 5]

array([1, 2, 3, 4, 5])

In [324]:
np.r_[1:9, 90,100]

array([  1,   2,   3,   4,   5,   6,   7,   8,  90, 100])

In [325]:
np.c_[1:5]

array([[1],
       [2],
       [3],
       [4]])

#### Разделение массивов

In [326]:
# разделение по горизонтали НА СТОЛБЦЫ
a = np.arange(10)
np.hsplit(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [327]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [328]:
# Так и по вертикали НА СТРОКИ
np.vsplit(a.reshape(-1, 1), 2)

[array([[0],
        [1],
        [2],
        [3],
        [4]]),
 array([[5],
        [6],
        [7],
        [8],
        [9]])]

In [329]:
# Можно разделятьи многомерные массивы
a = np.arange(12).reshape(2, 6)

In [330]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [331]:
np.hsplit(a, 2)

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11]])]

In [332]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

In [333]:
# Также можно разделять многомерный массив по определённой оси
a = np.arange(18).reshape(3, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [334]:
np.array_split(a, 2, axis=2)

[array([[[ 0],
         [ 2],
         [ 4]],
 
        [[ 6],
         [ 8],
         [10]],
 
        [[12],
         [14],
         [16]]]),
 array([[[ 1],
         [ 3],
         [ 5]],
 
        [[ 7],
         [ 9],
         [11]],
 
        [[13],
         [15],
         [17]]])]

###  Индексация, срезы и итерирование массивов

In [335]:
a = np.arange(10)

In [336]:
mask = a % 2 == 0

In [337]:
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [338]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [339]:
a[mask]

array([0, 2, 4, 6, 8])

In [340]:
a[a % 2 != 0]

array([1, 3, 5, 7, 9])

In [341]:
mask = np.array([[0, 1], [5, 6]])
a[mask]

array([[0, 1],
       [5, 6]])

###  Булевы операции и функции, значения inf и nan 

In [342]:
a = np.array([1, 15, -2, 16, 5])
b = np.array([12, 3, 9, 1, 5])

In [343]:
np.greater(a, b)

array([False,  True, False,  True, False])

In [344]:
np.greater_equal(a, b)

array([False,  True, False,  True,  True])

In [345]:
np.less(a, b)

array([ True, False,  True, False, False])

In [346]:
np.equal(a, b)

array([False, False, False, False,  True])

In [347]:
np.array_equal(a, b)

False

In [348]:
np.any(a > 10)

np.True_

In [349]:
np.any(a > 100)

np.False_

In [350]:
np.any(a == 5)

np.True_

In [351]:
np.all(a == 5)

np.False_

In [352]:
np.all(a < -100)

np.False_

In [353]:
a / 0

/var/folders/wp/_q09hw_d3wb__7f6fzdcg9p40000gn/T/ipykernel_9080/1979898162.py:1: RuntimeWarning: divide by zero encountered in divide
  a / 0


array([ inf,  inf, -inf,  inf,  inf])

In [354]:
b = np.array([1, 2, np.inf])
b

array([ 1.,  2., inf])

In [355]:
# при умножении inf на 0 получаем Not a Number (nan)
c = b * 0
c

/var/folders/wp/_q09hw_d3wb__7f6fzdcg9p40000gn/T/ipykernel_9080/1285892031.py:2: RuntimeWarning: invalid value encountered in multiply
  c = b * 0


array([ 0.,  0., nan])

In [356]:
# nan прилипчивый
c.sum()

np.float64(nan)

In [357]:
b = np.array([1, 2, np.nan, np.inf, -np.inf])
b

array([  1.,   2.,  nan,  inf, -inf])

In [358]:
np.isinf(b)

array([False, False, False,  True,  True])

In [359]:
np.isnan(b)

array([False, False,  True, False, False])

In [360]:
indx = np.isinf(b)
b[~indx]

array([ 1.,  2., nan])

In [361]:
# только конечные числовые значения np.isfinite()
np.isfinite(b)

array([ True,  True, False, False, False])

In [362]:
# также есть np.iscomplex() и np.isreal()
# для np.isreal() nan и inf считаются действительными числами
print(np.iscomplex(b))
print(np.isreal(b))

[False False False False False]
[ True  True  True  True  True]


In [363]:
X = np.array([True, False, True, False])
Y = np.array([True, True, False, False])

In [364]:
np.logical_and(X, Y)

array([ True, False, False, False])

In [365]:
np.logical_or(X, Y)

array([ True,  True,  True, False])

In [366]:
np.logical_not(X)

array([False,  True, False,  True])

In [367]:
# np.logical_xor - когда один элемент - True, второй - False
np.logical_xor(X, Y)

array([False,  True,  True, False])

In [368]:
# также работает с числовыми данными
a = [1, 0, 4, 0]
b = [2, 3, 0, 0]
print(np.logical_and(a, b))
print(np.logical_or(a, b))
print(np.logical_xor(a, b))
print(np.logical_not(a))

[ True False False False]
[ True  True  True False]
[False  True  True False]
[False  True False  True]


### Базовые математические функции