Материал для [Youtube курса по NumPy](https://www.youtube.com/playlist?list=PLA0M1Bcd0w8zmegfAUfFMiACPKfdW4ifD) от Сергея Балакирева


In [4]:
import numpy as np

### Основные типы данных. Создание массивов.

In [5]:
# при создании массива можно вторым аргументом указать необходимый тип данных
a = np.array([1, 2, 3], "float64")

In [6]:
a

array([1., 2., 3.])

In [7]:
# все возможные типы данных, которые поддерживает numpy
np.sctypeDict

{'bool': numpy.bool,
 'float16': numpy.float16,
 'float32': numpy.float32,
 'float64': numpy.float64,
 'longdouble': numpy.longdouble,
 'complex64': numpy.complex64,
 'complex128': numpy.complex128,
 'clongdouble': numpy.clongdouble,
 'bytes_': numpy.bytes_,
 'str_': numpy.str_,
 'void': numpy.void,
 'object_': numpy.object_,
 'datetime64': numpy.datetime64,
 'timedelta64': numpy.timedelta64,
 'int8': numpy.int8,
 'byte': numpy.int8,
 'uint8': numpy.uint8,
 'ubyte': numpy.uint8,
 'int16': numpy.int16,
 'short': numpy.int16,
 'uint16': numpy.uint16,
 'ushort': numpy.uint16,
 'int32': numpy.int32,
 'intc': numpy.int32,
 'uint32': numpy.uint32,
 'uintc': numpy.uint32,
 'int64': numpy.int64,
 'long': numpy.int64,
 'uint64': numpy.uint64,
 'ulong': numpy.uint64,
 'longlong': numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'intp': numpy.int64,
 'uintp': numpy.uint64,
 'double': numpy.float64,
 'cdouble': numpy.complex128,
 'single': numpy.float32,
 'csingle': numpy.complex64,
 'half': numpy.

In [8]:
a

array([1., 2., 3.])

In [9]:
# таким образом можно преобразовывать данные / массивы, создаётся копия
print(np.int8(16.999999999))
print(np.int8(a))

16
[1 2 3]


In [10]:
b = np.array([[1, 2], [3, 4], [5, 6]])

In [11]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [13]:
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [14]:
# к элементам можно обращаться так (равносильно c[1][0][1])
c[1, 0, 1]

np.int64(6)

In [15]:
c[1, 0, 1] == c[1][0][1]

np.True_

### Функции автозаполнения, создания матриц и числовых диапазонов.

In [16]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# np.empty(shape, ...)
# Возвращает новый массив заданного размера и типа данных, но без определённых значений.
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# np.eye(N, M=None, ...)
# Возвращает массив размером N*M с единичными диагональными элементами (остальные равны 0)
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [20]:
# np.identity(n, ...)
# Возвращает квадратный массив с единичными диагональными элементами (остальные равны 0)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# np.zeros(shape, ...)
# Возвращает массив заданного размера и типа, состоящего из всех нулей
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# np.ones(shape, ...)
# Возвращает массив заданного размера и типа, состоящего из всех единиц
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# np.full(shape, value, ...)
# Возвращает массив заданного размера и типа со значениями value.
np.full((2, 3), 11)

array([[11, 11, 11],
       [11, 11, 11]])

In [24]:
# np.asmatrix("str")
# создаёт матрицу из строки
np.asmatrix("1 2 3 4")
# np.asmatrix("1 2 3 4") == np.asmatrix("1, 2, 3, 4")

matrix([[1, 2, 3, 4]])

In [25]:
# через ; можно создавать двумерную матрицу
np.asmatrix("1 2 3; 4 5 6")
# np.asmatrix("1 2 3; 4 5 6") == np.mat([(1, 2, 3), (4, 5, 6)])
# np.asmatrix("1 2 3; 4 5 6") == np.asmatrix([(1, 2, 3), (4, 5, 6)])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [26]:
# np.diag([a, b, c])
# создает матрицу, где на главной диагонали будут элементы a, b, c
np.diag([1, 2, 5])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 5]])

In [27]:
# Если в np.diag передать двумерный список или массив
# то эта функция выделяет элементы, стоящие на главной диагонали
np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([1, 5, 9])

In [28]:
# np.tri(shape)
# создаёт матрицу размером shape где все элементы на главной диагонали и под ней - единицы
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [29]:
np.tri(4, 2)

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
# Если в np.tril передать массив, то обнулятся все элементы над главной диагональю
a = np.arange(9).reshape(3, 3)

In [31]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.tril(a)

array([[0, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [33]:
# Обратно работает np.triu
np.triu(np.arange(9).reshape(3, 3))

array([[0, 1, 2],
       [0, 4, 5],
       [0, 0, 8]])

Название | Описание
--- | ---
arange() | Возвращает одномерный массив с равномерно разнесёнными числами указанного диапазаона.
linspace(start, stop, ...) | Возвращает одномерный массив с равномерно разнесёнными числами, используя только значения начала и конца интервала.
logspace(start, stop, ...) | Возвращает одномерный массив с числами, равномерно распределённых по логарифмической шкале.
geomspace(start, stop, ...) | Формирование чисел по геометрической прогрессии.
meshgrid(x1, ..., xn, ...) | x1, ..., xn - одномерные последовательности или массивы, используемые для формирования координатной сетки по каждой из осей.
mgrid[] | Возвращает массив плотных координатных сеток.
ogrid[] | Возвращает открытую сетку значений.

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
# Можно указывать вещественные значения и константы
np.arange(1, 5, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [36]:
# np.linspace
# при указании в качестве количества значений
# 1 - получим только начало диапазона
# 2 - начало и конец
# 3 - начало, конец и среднее арифметическое
# и т. д.
for i in range(1, 5):
    print(np.linspace(0, np.pi, i))

[0.]
[0.         3.14159265]
[0.         1.57079633 3.14159265]
[0.         1.04719755 2.0943951  3.14159265]


In [37]:
# np.logspace - логарифмическая шкала
for i in range(1, 5):
    print(np.logspace(0, 3, i))


[1.]
[   1. 1000.]
[   1.          31.6227766 1000.       ]
[   1.   10.  100. 1000.]


In [38]:
# np.geomspace геометрическая прогрессия
np.geomspace(1, 16, 5)

array([ 1.,  2.,  4.,  8., 16.])

Фнукции формирования массивов на основе данных
Название | Описание
--- | ---
array(object, ...) | Преобразует список или кортеж object в массив NumPy.
asanyarray(list, ...) | Преобразует список list в массив array, сохраняя тип подкласса.
ascontiguousarray(list, ...) | Возвращает непрерывный массив в памяти, подобно как это организовано в языке C.
asmatrix(list, ...) | Преобразует входную последовательность list в матрицу NumPy (тип matrix).
copy(list, ...) | Возвращает копию массива list (если это объект Numpy) или просто создаёт массив на основе списка языка Python.
frombuffer(buffer, ...) | Преобразует данные из буфера в массив NumPy.
fromfile(file, ...) | Возвращает массив из данных текстового или бинарного файла file.
fromfunction(func, shape, ...) | Создаёт массив размерностью shape с помощью функции func.
fromiter(iter, ...) | Создаёт массив на основе итерируемого объекта.
fromstring(string, ...) | Создаёт массив из данных строки.
loadtxt(file, ...) | Формирует массив из данных текстового файла.

In [39]:
a = np.array([[1, 2], [3, 4]])
b = a

In [40]:
b[0][1] = 100
b

array([[  1, 100],
       [  3,   4]])

In [41]:
a

array([[  1, 100],
       [  3,   4]])

In [42]:
c = np.copy(a)

In [43]:
c[0][1] = - 1000
print(c, a, sep='\n')

[[    1 -1000]
 [    3     4]]
[[  1 100]
 [  3   4]]


### Свойства и представления массивов, создание их копий

In [44]:
a = np.array([.1, .2, .3, .4, .5, .6, .7, .8, .9,])
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [45]:
# количество элементов
a.size

9

In [46]:
# размер одного элемента в байтах
a .itemsize

8

In [47]:
# Общее количество байтов для массива
a.size * a.itemsize

72

In [48]:
b = np.ones((3, 4, 5))

In [49]:
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [50]:
# Количество осей
b.ndim

3

In [51]:
# Форма массива
b.shape

(3, 4, 5)

In [52]:
# Изменение формы массива
b.shape = (12, 5)
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
c = b.reshape((2, 2, 15))
c

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [55]:
a = np.array([x for x in range(1, 10)])
b = a.view() # .view() создаёт копию представления
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a.shape = 3, 3
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
b # представление b не изменилось в следствие изменение формы массива а

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a[0][0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [59]:
b # но при внесении изменений в a, массив b также изменился
# но при использовании b = a.copy() или b = np.array(a), создаётся копия массива
# и при внесении изменений в один массив, другой будет оставаться неизменным.

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

### Изменение формы массивов, добавление и удаление осей

In [60]:
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [61]:
# Изменить форму представления так, чтобы стало 3 столбца
a.shape = -1, 3
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [62]:
a.reshape(-1, 1)

array([[100],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [63]:
a.reshape(1, -1)

array([[100,   2,   3,   4,   5,   6,   7,   8,   9]])

In [64]:
# вытягивает массив в вектор
a.ravel()

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [65]:
a = np.arange(1, 16)
a.resize((5, 3))
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [66]:
# reshape создаёт новый массив с новой формой
# resize изменяет исходный массив и не создаёт новый (возвращает None)

In [67]:
x_test = np.arange(32).reshape(8, 2, 2)
x_test

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [68]:
# expand_dims добавляет новые оси, но создаёт новое представление массива
x_test_new = np.expand_dims(x_test, axis=0)
x_test_new.shape

(1, 8, 2, 2)

In [69]:
x_test_new[0, 0, 0, 0] = -100
x_test

array([[[-100,    1],
        [   2,    3]],

       [[   4,    5],
        [   6,    7]],

       [[   8,    9],
        [  10,   11]],

       [[  12,   13],
        [  14,   15]],

       [[  16,   17],
        [  18,   19]],

       [[  20,   21],
        [  22,   23]],

       [[  24,   25],
        [  26,   27]],

       [[  28,   29],
        [  30,   31]]])

In [70]:
a = np.append(x_test_new, x_test_new, axis=0)
a.shape

(2, 8, 2, 2)

In [71]:
# delete удаляет указанный элемент (откуда, индекс, по какой оси)
b = np.delete(a, 0, axis=0)
b.shape

(1, 8, 2, 2)

In [72]:
c = np.delete(a, 0, axis=1)
c.shape

(2, 7, 2, 2)

In [73]:
d = np.expand_dims(x_test_new, axis=-1)
d.shape

(1, 8, 2, 2, 1)

In [74]:
# np.squeeze удаляет все оси, у которых есть только один элемент
e = np.squeeze(d)
e.shape

(8, 2, 2)

In [75]:
# или же можно удалить конкретную ось
e = np.squeeze(d, axis=0)
e.shape

(8, 2, 2, 1)

In [76]:
# при указании оси, в которой более одного элемента, возникнет ошибка
try:
    e = np.squeeze(d, axis=2)
except Exception as e:
    print(f"Exception: {e}.")

Exception: cannot select an axis to squeeze out which has size not equal to one.


In [77]:
a = np.arange(1, 10)
a.shape

(9,)

In [78]:
# newaxis добавляет новую ось
b = a[np.newaxis, :]
b.shape

(1, 9)

In [79]:
b = a[:, np.newaxis]
b.shape

(9, 1)

### Объединение и разделение массивов

#### Объединение массивов

In [80]:
a = np.array([(1, 2), (3, 4)])
b = np.array([(5, 6), (7, 8)])

In [81]:
print(a, b, sep="\n")

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [82]:
# hstack возвращает копию массивов a и b, объединённых по горизонтали.
np.hstack([a, b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [83]:
# hstack возвращает копию массивов a и b, объединённых по вертикали.
np.vstack([a, b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [84]:
a = a.ravel()
b = b.ravel()

In [85]:
print(np.hstack([a, b]))
print(np.vstack([a, b]))
print(np.column_stack([a, b]))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [86]:
a = np.arange(1, 13)
b = np.arange(13, 26)
a.resize(3, 3, 2)
b.resize(3, 3, 2)

In [87]:
c0 = np.concatenate([a, b], axis=0)
c1 = np.concatenate([a, b], axis=1)
c2 = np.concatenate([a, b], axis=2)
print(c0.shape, c1.shape, c2.shape)

(6, 3, 2) (3, 6, 2) (3, 3, 4)


In [88]:
np.r_[[1, 2, 3], 4, 5]

array([1, 2, 3, 4, 5])

In [89]:
np.r_[1:9, 90,100]

array([  1,   2,   3,   4,   5,   6,   7,   8,  90, 100])

In [90]:
np.c_[1:5]

array([[1],
       [2],
       [3],
       [4]])

#### Разделение массивов

In [91]:
# разделение по горизонтали НА СТОЛБЦЫ
a = np.arange(10)
np.hsplit(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [92]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [93]:
# Так и по вертикали НА СТРОКИ
np.vsplit(a.reshape(-1, 1), 2)

[array([[0],
        [1],
        [2],
        [3],
        [4]]),
 array([[5],
        [6],
        [7],
        [8],
        [9]])]

In [94]:
# Можно разделятьи многомерные массивы
a = np.arange(12).reshape(2, 6)

In [95]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [96]:
np.hsplit(a, 2)

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11]])]

In [97]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

In [98]:
# Также можно разделять многомерный массив по определённой оси
a = np.arange(18).reshape(3, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [99]:
np.array_split(a, 2, axis=2)

[array([[[ 0],
         [ 2],
         [ 4]],
 
        [[ 6],
         [ 8],
         [10]],
 
        [[12],
         [14],
         [16]]]),
 array([[[ 1],
         [ 3],
         [ 5]],
 
        [[ 7],
         [ 9],
         [11]],
 
        [[13],
         [15],
         [17]]])]

###  Индексация, срезы и итерирование массивов

In [100]:
a = np.arange(10)

In [101]:
mask = a % 2 == 0

In [102]:
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [103]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
a[mask]

array([0, 2, 4, 6, 8])

In [105]:
a[a % 2 != 0]

array([1, 3, 5, 7, 9])

In [106]:
mask = np.array([[0, 1], [5, 6]])
a[mask]

array([[0, 1],
       [5, 6]])

###  Булевы операции и функции, значения inf и nan 

In [107]:
a = np.array([1, 15, -2, 16, 5])
b = np.array([12, 3, 9, 1, 5])

In [108]:
np.greater(a, b)

array([False,  True, False,  True, False])

In [109]:
np.greater_equal(a, b)

array([False,  True, False,  True,  True])

In [110]:
np.less(a, b)

array([ True, False,  True, False, False])

In [111]:
np.equal(a, b)

array([False, False, False, False,  True])

In [112]:
np.array_equal(a, b)

False

In [113]:
np.any(a > 10)

np.True_

In [114]:
np.any(a > 100)

np.False_

In [115]:
np.any(a == 5)

np.True_

In [116]:
np.all(a == 5)

np.False_

In [117]:
np.all(a < -100)

np.False_

In [118]:
a / 0

/var/folders/wp/_q09hw_d3wb__7f6fzdcg9p40000gn/T/ipykernel_23637/1979898162.py:1: RuntimeWarning: divide by zero encountered in divide
  a / 0


array([ inf,  inf, -inf,  inf,  inf])

In [119]:
b = np.array([1, 2, np.inf])
b

array([ 1.,  2., inf])

In [120]:
# при умножении inf на 0 получаем Not a Number (nan)
c = b * 0
c

/var/folders/wp/_q09hw_d3wb__7f6fzdcg9p40000gn/T/ipykernel_23637/1285892031.py:2: RuntimeWarning: invalid value encountered in multiply
  c = b * 0


array([ 0.,  0., nan])

In [121]:
# nan прилипчивый
c.sum()

np.float64(nan)

In [122]:
b = np.array([1, 2, np.nan, np.inf, -np.inf])
b

array([  1.,   2.,  nan,  inf, -inf])

In [123]:
np.isinf(b)

array([False, False, False,  True,  True])

In [124]:
np.isnan(b)

array([False, False,  True, False, False])

In [125]:
indx = np.isinf(b)
b[~indx]

array([ 1.,  2., nan])

In [126]:
# только конечные числовые значения np.isfinite()
np.isfinite(b)

array([ True,  True, False, False, False])

In [127]:
# также есть np.iscomplex() и np.isreal()
# для np.isreal() nan и inf считаются действительными числами
print(np.iscomplex(b))
print(np.isreal(b))

[False False False False False]
[ True  True  True  True  True]


In [128]:
X = np.array([True, False, True, False])
Y = np.array([True, True, False, False])

In [129]:
np.logical_and(X, Y)

array([ True, False, False, False])

In [130]:
np.logical_or(X, Y)

array([ True,  True,  True, False])

In [131]:
np.logical_not(X)

array([False,  True, False,  True])

In [132]:
# np.logical_xor - когда один элемент - True, второй - False
np.logical_xor(X, Y)

array([False,  True,  True, False])

In [133]:
# также работает с числовыми данными
a = [1, 0, 4, 0]
b = [2, 3, 0, 0]
print(np.logical_and(a, b))
print(np.logical_or(a, b))
print(np.logical_xor(a, b))
print(np.logical_not(a))

[ True False False False]
[ True  True  True False]
[False  True  True False]
[False  True False  True]


### Базовые математические функции

In [134]:
a = np.array([1, 2, 3, 10, 20, 30])

In [135]:
a.mean()

np.float64(11.0)

In [136]:
a.max()

np.int64(30)

In [137]:
a.min()

np.int64(1)

In [138]:
a.sum()

np.int64(66)

In [139]:
a.resize(3, 2)
a

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [140]:
a.sum()

np.int64(66)

In [141]:
a.sum(axis=0)

array([24, 42])

In [142]:
a.sum(axis=1)

array([ 3, 13, 50])

Название | Описание
--- | ---
np.abs(x) | Вычисление модуля от аргумента(ов) x; x может быть числом, списком или массивом
np.amax(x) | Нахождение максимального значения от аргумента(ов) x
np.amin(x) | Нахождение минимального значения от аргумента(ов) x
np.agrmax(x) | Нахождение индекса максимального значения для x 
np.argmin(x) | Нахождение индекса минимального значения для x
np.around(x) | Округление до ближайшего целого
np.mean(x) | Вычисление среднего значения
np.log(x) | Вычисление натурального логарифма
np.log2(x) | Вычисление логарифма по основанию 2
nplog10(x) | Вычисление алгоритма по основанию 10

In [143]:
a = np.arange(-3, 3)

In [144]:
np.abs(a)

array([3, 2, 1, 0, 1, 2])

Тригонометрические функции
Название | Описание
--- | ---
np.sin(x) | Вычисление синуса угла(ов) x (в радианах), x может быть числом, списком, массивом
np.cos(x) | Вычисление косинуса угла(ов) x 
np.tan(x) | Вычисление тангенса угла(ов) x 
np.arcsin(x) | Арксинус угла(ов) х
np.arccos(x) | Арккосинус угла(ов) х
np.arctan(x) | Арктангенс угла(ов) х


In [145]:
a = np.linspace(0, np.pi, 10)
a

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [146]:
np.sin(a)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

#### Функции генерации псевдослучайных чисел
Название | Описание
--- | ---
np.random.rand() | Генерация числе с равномерным законом распределения от 0 до 1 не включая 1
np.random.randint() | Генерация целоых чисел с равномерным законом распределения
np.random.randn() | Генерация нормальных случайных значений
np.random.seed() | Установка начального состояния генератора

In [147]:
np.random.rand()

0.9725031215518961

In [148]:
np.random.rand(5)

array([0.22761117, 0.7998424 , 0.24074056, 0.14996858, 0.0437448 ])

In [149]:
np.random.rand(2, 3)

array([[0.37902349, 0.7023372 , 0.45713124],
       [0.42361136, 0.2670794 , 0.14636657]])

In [150]:
np.random.randint(5)

1

In [151]:
np.random.randint(5, 10)

6

In [152]:
np.random.randint(5, size=4)

array([1, 4, 0, 3])

In [153]:
np.random.randint(5, size=(2, 3))

array([[3, 3, 3],
       [0, 2, 0]])

In [154]:
np.random.randn() # Случайные величины с нулевым математическим ожиданием и единичной дисперсией

1.9929342232796967

In [155]:
# Существует множество функий для генерации разных распределений, информация в документации.

In [156]:
# особенность работы псевдослучайной генерации
for _ in range(3):
    np.random.seed(7)
    print(np.random.randint(10, size=10))
    print(np.random.randint(10, size=10))

[4 9 6 3 3 7 7 9 7 8]
[9 8 7 6 4 0 7 0 7 6]
[4 9 6 3 3 7 7 9 7 8]
[9 8 7 6 4 0 7 0 7 6]
[4 9 6 3 3 7 7 9 7 8]
[9 8 7 6 4 0 7 0 7 6]


In [157]:
a = np.random.randint(10, size=10)
a

array([3, 5, 8, 8, 7, 5, 0, 0, 2, 8])

In [158]:
np.random.shuffle(a)
a

array([8, 5, 3, 0, 8, 5, 2, 7, 0, 8])

In [159]:
np.random.permutation(5) + 1

array([4, 3, 5, 2, 1])

In [160]:
# можно передать и массив
np.random.permutation(a)


array([8, 8, 5, 8, 0, 5, 3, 0, 7, 2])

#### Функции математической статистики
Название | Описание
--- | ---
np.median(x) | Вычисление медианы величин x
np.var(x) | Дисперсия величин x
np.std(x) | Среднеквадратическое отклонение величин x
np.corrcoef(x) | Линейный коэффициент корреляции Пирсона
np.correlate(x) | Вычисление кросс-корреляции
np.cov(x) | Вычисление ковариационной матрицы

In [161]:
x = np.array([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])
y = np.array([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])

In [162]:
np.median(x)

np.float64(9.0)

In [163]:
np.var(x)

np.float64(57.29)

In [164]:
np.std(x)

np.float64(7.569015788066504)

In [165]:
XY = np.vstack([x, y])
XY

array([[ 1,  4,  3,  7, 10,  8, 14, 21, 20, 23],
       [ 4,  1,  6,  9, 13, 11, 16, 19, 15, 22]])

In [166]:
np.corrcoef(XY)

array([[1.        , 0.93158099],
       [0.93158099, 1.        ]])

In [167]:
np.cov(XY)

array([[63.65555556, 49.82222222],
       [49.82222222, 44.93333333]])

In [168]:
np.correlate(x, y)

array([1736])

### Произведение матриц и векторов, элементы линейной алгебры

In [169]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
b = np.arange(18, 27).reshape(3, 3)
b

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [171]:
a * b

array([[ 18,  38,  60],
       [ 84, 110, 138],
       [168, 200, 234]])

In [172]:
# умножение матриц
np.matmul(a, b)

array([[132, 138, 144],
       [321, 336, 351],
       [510, 534, 558]])

In [173]:
a.shape = -1, 1

In [174]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [175]:
# для умножения матрицы должны быть согласованы
try:
    np.dot(a, b)
except Exception as e:
    print(e)

shapes (9,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)


In [176]:
# с момошью .dot можно умножать и вектора
a = np.arange(1, 10)
b = np.ones(9)

In [177]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [179]:
np.dot(a, b)

np.float64(45.0)

In [180]:
# предпочтительнее использовать np.inner
np.inner(a, b)

np.float64(45.0)

In [181]:
np.outer(b, a)

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [182]:
# также можем использовать @
a @ b

np.float64(45.0)

In [183]:
a.resize(3, 3)
b.resize(3, 3)

In [184]:
a @ b

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [185]:
# решение системы уравнений
a = np.array([[1, 2, 3], [1, 4, 9], [1, 8, 27]])
y = np.array([10, 20, 30])

In [186]:
np.linalg.solve(a, y)

array([-5.        , 10.        , -1.66666667])

Возможности linalg
Функция | Описание
--- | ---
linalg.cholesky() | Разложение Холецкого
linalg.qr() | QR-разложение матрицы
linalg.svd() | Сингулярное (SVD) разложение маьрицы
linalg.norm() | Норма матрицы или вектора
linalg.cond() | Число обусловленности матрицы
linalg.det() | Определитель (детерминант) матрицы
linalg.matrix_rank() | Вычисление ранга матрицы по алгоритму SVD
np.trace() | Сумма диагональных элементов массива
linalg.eig() | Вычисление собственных значений и правых собственных векторов
linalg.eigvals() | Вычисление собственных значений матрицы
linalg.solve() | Решение линейного матричного уравнения
linalg.tensorsolve() | Решение линейного тензорного уравнения
linalg.lstsq() | Решение задачи поиска наименьших квадратов для линейного матричного уравнения
linalg.inv() | Вычисление обратной матрицы
linalg.pinv() | Вычисление псевдообратной (Мура-Пенроуза) матрицы 
linalg.tensorinv() | Вычисление обратного тензора (N-мерного массива)


### Множества и операции над ними

In [187]:
a = np.array([1, 2, 3, 4, 4, 3, 2, 1])
a

array([1, 2, 3, 4, 4, 3, 2, 1])

In [188]:
setA = np.unique(a)
setA

array([1, 2, 3, 4])

In [189]:
# параметр return_counts позволяет посчитать количество вхождений
np.unique(a, return_counts=True)

(array([1, 2, 3, 4]), array([2, 2, 2, 2]))

In [190]:
# параметр return_index позволяет получить индексы первого включения
np.unique(a, return_index=True)

(array([1, 2, 3, 4]), array([0, 1, 2, 3]))

In [191]:
# параметр return_invers позволяет восстановить массив
np.unique(a, return_inverse=True)

(array([1, 2, 3, 4]), array([0, 1, 2, 3, 3, 2, 1, 0]))

In [192]:
setA, indx = np.unique(a, return_inverse=True)

In [193]:
setA[indx]

array([1, 2, 3, 4, 4, 3, 2, 1])

In [194]:
x = np.array([0, 1, 2, 3])
y = np.arange(1, 9)
x, y

(array([0, 1, 2, 3]), array([1, 2, 3, 4, 5, 6, 7, 8]))

In [195]:
# Показывает маску вхождения элементов массива x в массив y
np.isin(x, y)

array([False,  True,  True,  True])

In [196]:
# Причём вхождение проверяется во множествах,
# поэтому положение элементов не имеент значения
np.random.shuffle(y)
np.isin(x, y)

array([False,  True,  True,  True])

In [197]:
# np.intersect1d - пересечение множеств
np.intersect1d(x, y)

array([1, 2, 3])

In [198]:
# np.union1d - объединение множеств
np.union1d(x, y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [199]:
# np.setdiff1d(x, y) разность множеств, положение имеет значение
np.setdiff1d(x, y)

array([0])

In [200]:
np.setdiff1d(y, x)

array([4, 5, 6, 7, 8])

In [201]:
# np.setxor1d - симметричная разность
np.setxor1d(x, y)

array([0, 4, 5, 6, 7, 8])

### Транслирование массивов (broadcasting)

In [202]:
a = np.array([1, 2, 3, 10, 20, 30])
b = ([2])

In [203]:
a * b

array([ 2,  4,  6, 20, 40, 60])

In [204]:
a + b

array([ 3,  4,  5, 12, 22, 32])

In [205]:
b = [2, 3]

In [206]:
try:
    a * b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (6,) (2,) 


Правила транслирования массивов:  
1. Если массивы имеют разное число осей, то к массиву с меньшим их числом добаляются новые так, чтобы размеры совпадали (Причём добавление всегда происходит с оси axis=0).
2. Оси с одним элементом расширяются (по числу элементов) так, чтобы соответствующие размерности двух массивов совпадали.

In [207]:
a = np.arange(6).reshape(3, 1, 2)
b = np.ones(4).reshape(2, 2)

In [211]:
c = a * b
c

array([[[0., 1.],
        [0., 1.]],

       [[2., 3.],
        [2., 3.]],

       [[4., 5.],
        [4., 5.]]])

In [225]:
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.array([7, 8, 9, 10])

In [226]:
try:
    c = a * b + c
except Exception as e:
    print(f"Не может быть выполнено: {e}")

Не может быть выполнено: operands could not be broadcast together with shapes (3,) (2,) 


In [230]:
print(f"{a.shape=}, {b.shape=}, {c.shape=}")
an, bn, cn = np.ix_(a, b, c)
print(f"{an.shape=}, {bn.shape=}, {cn.shape=}")

a.shape=(3,), b.shape=(2,), c.shape=(4,)
an.shape=(3, 1, 1), bn.shape=(1, 2, 1), cn.shape=(1, 1, 4)


In [231]:
d = an * bn + cn
d

array([[[11, 12, 13, 14],
        [12, 13, 14, 15]],

       [[15, 16, 17, 18],
        [17, 18, 19, 20]],

       [[19, 20, 21, 22],
        [22, 23, 24, 25]]])