Материал для [Youtube курса по NumPy](https://www.youtube.com/playlist?list=PLA0M1Bcd0w8zmegfAUfFMiACPKfdW4ifD) от Сергея Балакирева


In [1]:
import numpy as np

### Основные типы данных. Создание массивов.

In [2]:
# при создании массива можно вторым аргументом указать необходимый тип данных
a = np.array([1, 2, 3], "float64")

In [3]:
a

array([1., 2., 3.])

In [4]:
# все возможные типы данных, которые поддерживает numpy
np.sctypeDict

{'bool': numpy.bool,
 'float16': numpy.float16,
 'float32': numpy.float32,
 'float64': numpy.float64,
 'longdouble': numpy.longdouble,
 'complex64': numpy.complex64,
 'complex128': numpy.complex128,
 'clongdouble': numpy.clongdouble,
 'bytes_': numpy.bytes_,
 'str_': numpy.str_,
 'void': numpy.void,
 'object_': numpy.object_,
 'datetime64': numpy.datetime64,
 'timedelta64': numpy.timedelta64,
 'int8': numpy.int8,
 'byte': numpy.int8,
 'uint8': numpy.uint8,
 'ubyte': numpy.uint8,
 'int16': numpy.int16,
 'short': numpy.int16,
 'uint16': numpy.uint16,
 'ushort': numpy.uint16,
 'int32': numpy.int32,
 'intc': numpy.int32,
 'uint32': numpy.uint32,
 'uintc': numpy.uint32,
 'int64': numpy.int64,
 'long': numpy.int64,
 'uint64': numpy.uint64,
 'ulong': numpy.uint64,
 'longlong': numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'intp': numpy.int64,
 'uintp': numpy.uint64,
 'double': numpy.float64,
 'cdouble': numpy.complex128,
 'single': numpy.float32,
 'csingle': numpy.complex64,
 'half': numpy.

In [5]:
a

array([1., 2., 3.])

In [6]:
# таким образом можно преобразовывать данные / массивы, создаётся копия
print(np.int8(16.999999999))
print(np.int8(a))

16
[1 2 3]


In [7]:
b = np.array([[1, 2], [3, 4], [5, 6]])

In [8]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [10]:
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [11]:
# к элементам можно обращаться так (равносильно c[1][0][1])
c[1, 0, 1]

np.int64(6)

In [12]:
c[1, 0, 1] == c[1][0][1]

np.True_

### Функции автозаполнения, создания матриц и числовых диапазонов.

In [13]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# np.empty(shape, ...)
# Возвращает новый массив заданного размера и типа данных, но без определённых значений.
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# np.eye(N, M=None, ...)
# Возвращает массив размером N*M с единичными диагональными элементами (остальные равны 0)
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [17]:
# np.identity(n, ...)
# Возвращает квадратный массив с единичными диагональными элементами (остальные равны 0)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# np.zeros(shape, ...)
# Возвращает массив заданного размера и типа, состоящего из всех нулей
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# np.ones(shape, ...)
# Возвращает массив заданного размера и типа, состоящего из всех единиц
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# np.full(shape, value, ...)
# Возвращает массив заданного размера и типа со значениями value.
np.full((2, 3), 11)

array([[11, 11, 11],
       [11, 11, 11]])

In [21]:
# np.asmatrix("str")
# создаёт матрицу из строки
np.asmatrix("1 2 3 4")
# np.asmatrix("1 2 3 4") == np.asmatrix("1, 2, 3, 4")

matrix([[1, 2, 3, 4]])

In [22]:
# через ; можно создавать двумерную матрицу
np.asmatrix("1 2 3; 4 5 6")
# np.asmatrix("1 2 3; 4 5 6") == np.mat([(1, 2, 3), (4, 5, 6)])
# np.asmatrix("1 2 3; 4 5 6") == np.asmatrix([(1, 2, 3), (4, 5, 6)])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [23]:
# np.diag([a, b, c])
# создает матрицу, где на главной диагонали будут элементы a, b, c
np.diag([1, 2, 5])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 5]])

In [24]:
# Если в np.diag передать двумерный список или массив
# то эта функция выделяет элементы, стоящие на главной диагонали
np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([1, 5, 9])

In [25]:
# np.tri(shape)
# создаёт матрицу размером shape где все элементы на главной диагонали и под ней - единицы
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [26]:
np.tri(4, 2)

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
# Если в np.tril передать массив, то обнулятся все элементы над главной диагональю
a = np.arange(9).reshape(3, 3)

In [28]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
np.tril(a)

array([[0, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [30]:
# Обратно работает np.triu
np.triu(np.arange(9).reshape(3, 3))

array([[0, 1, 2],
       [0, 4, 5],
       [0, 0, 8]])

Название | Описание
--- | ---
arange() | Возвращает одномерный массив с равномерно разнесёнными числами указанного диапазаона.
linspace(start, stop, ...) | Возвращает одномерный массив с равномерно разнесёнными числами, используя только значения начала и конца интервала.
logspace(start, stop, ...) | Возвращает одномерный массив с числами, равномерно распределённых по логарифмической шкале.
geomspace(start, stop, ...) | Формирование чисел по геометрической прогрессии.
meshgrid(x1, ..., xn, ...) | x1, ..., xn - одномерные последовательности или массивы, используемые для формирования координатной сетки по каждой из осей.
mgrid[] | Возвращает массив плотных координатных сеток.
ogrid[] | Возвращает открытую сетку значений.

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
# Можно указывать вещественные значения и константы
np.arange(1, 5, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [33]:
# np.linspace
# при указании в качестве количества значений
# 1 - получим только начало диапазона
# 2 - начало и конец
# 3 - начало, конец и среднее арифметическое
# и т. д.
for i in range(1, 5):
    print(np.linspace(0, np.pi, i))

[0.]
[0.         3.14159265]
[0.         1.57079633 3.14159265]
[0.         1.04719755 2.0943951  3.14159265]


In [34]:
# np.logspace - логарифмическая шкала
for i in range(1, 5):
    print(np.logspace(0, 3, i))


[1.]
[   1. 1000.]
[   1.          31.6227766 1000.       ]
[   1.   10.  100. 1000.]


In [35]:
# np.geomspace геометрическая прогрессия
np.geomspace(1, 16, 5)

array([ 1.,  2.,  4.,  8., 16.])

Фнукции формирования массивов на основе данных
Название | Описание
--- | ---
array(object, ...) | Преобразует список или кортеж object в массив NumPy.
asanyarray(list, ...) | Преобразует список list в массив array, сохраняя тип подкласса.
ascontiguousarray(list, ...) | Возвращает непрерывный массив в памяти, подобно как это организовано в языке C.
asmatrix(list, ...) | Преобразует входную последовательность list в матрицу NumPy (тип matrix).
copy(list, ...) | Возвращает копию массива list (если это объект Numpy) или просто создаёт массив на основе списка языка Python.
frombuffer(buffer, ...) | Преобразует данные из буфера в массив NumPy.
fromfile(file, ...) | Возвращает массив из данных текстового или бинарного файла file.
fromfunction(func, shape, ...) | Создаёт массив размерностью shape с помощью функции func.
fromiter(iter, ...) | Создаёт массив на основе итерируемого объекта.
fromstring(string, ...) | Создаёт массив из данных строки.
loadtxt(file, ...) | Формирует массив из данных текстового файла.

In [36]:
a = np.array([[1, 2], [3, 4]])
b = a

In [37]:
b[0][1] = 100
b

array([[  1, 100],
       [  3,   4]])

In [38]:
a

array([[  1, 100],
       [  3,   4]])

In [39]:
c = np.copy(a)

In [40]:
c[0][1] = - 1000
print(c, a, sep='\n')

[[    1 -1000]
 [    3     4]]
[[  1 100]
 [  3   4]]


### Свойства и представления массивов, создание их копий

In [41]:
a = np.array([.1, .2, .3, .4, .5, .6, .7, .8, .9,])
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [42]:
# количество элементов
a.size

9

In [43]:
# размер одного элемента в байтах
a .itemsize

8

In [44]:
# Общее количество байтов для массива
a.size * a.itemsize

72

In [45]:
b = np.ones((3, 4, 5))

In [46]:
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [47]:
# Количество осей
b.ndim

3

In [48]:
# Форма массива
b.shape

(3, 4, 5)

In [49]:
# Изменение формы массива
b.shape = (12, 5)
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
c = b.reshape((2, 2, 15))
c

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [52]:
a = np.array([x for x in range(1, 10)])
b = a.view() # .view() создаёт копию представления
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a.shape = 3, 3
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
b # представление b не изменилось в следствие изменение формы массива а

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a[0][0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [56]:
b # но при внесении изменений в a, массив b также изменился
# но при использовании b = a.copy() или b = np.array(a), создаётся копия массива
# и при внесении изменений в один массив, другой будет оставаться неизменным.

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

### Изменение формы массивов, добавление и удаление осей

In [57]:
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [58]:
# Изменить форму представления так, чтобы стало 3 столбца
a.shape = -1, 3
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [59]:
a.reshape(-1, 1)

array([[100],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [60]:
a.reshape(1, -1)

array([[100,   2,   3,   4,   5,   6,   7,   8,   9]])

In [61]:
# вытягивает массив в вектор
a.ravel()

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [62]:
a = np.arange(1, 16)
a.resize((5, 3))
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [63]:
# reshape создаёт новый массив с новой формой
# resize изменяет исходный массив и не создаёт новый (возвращает None)

In [64]:
x_test = np.arange(32).reshape(8, 2, 2)
x_test

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [65]:
# expand_dims добавляет новые оси, но создаёт новое представление массива
x_test_new = np.expand_dims(x_test, axis=0)
x_test_new.shape

(1, 8, 2, 2)

In [66]:
x_test_new[0, 0, 0, 0] = -100
x_test

array([[[-100,    1],
        [   2,    3]],

       [[   4,    5],
        [   6,    7]],

       [[   8,    9],
        [  10,   11]],

       [[  12,   13],
        [  14,   15]],

       [[  16,   17],
        [  18,   19]],

       [[  20,   21],
        [  22,   23]],

       [[  24,   25],
        [  26,   27]],

       [[  28,   29],
        [  30,   31]]])

In [67]:
a = np.append(x_test_new, x_test_new, axis=0)
a.shape

(2, 8, 2, 2)

In [68]:
# delete удаляет указанный элемент (откуда, индекс, по какой оси)
b = np.delete(a, 0, axis=0)
b.shape

(1, 8, 2, 2)

In [69]:
c = np.delete(a, 0, axis=1)
c.shape

(2, 7, 2, 2)

In [70]:
d = np.expand_dims(x_test_new, axis=-1)
d.shape

(1, 8, 2, 2, 1)

In [71]:
# np.squeeze удаляет все оси, у которых есть только один элемент
e = np.squeeze(d)
e.shape

(8, 2, 2)

In [72]:
# или же можно удалить конкретную ось
e = np.squeeze(d, axis=0)
e.shape

(8, 2, 2, 1)

In [73]:
# при указании оси, в которой более одного элемента, возникнет ошибка
try:
    e = np.squeeze(d, axis=2)
except Exception as e:
    print(f"Exception: {e}.")

Exception: cannot select an axis to squeeze out which has size not equal to one.


In [74]:
a = np.arange(1, 10)
a.shape

(9,)

In [75]:
# newaxis добавляет новую ось
b = a[np.newaxis, :]
b.shape

(1, 9)

In [76]:
b = a[:, np.newaxis]
b.shape

(9, 1)

### Объединение и разделение массивов