In [2]:
import numpy as np

### Основные типы данных. Создание массивов.

In [3]:
# при создании массива можно вторым аргументом указать необходимый тип данных
a = np.array([1, 2, 3], "float64")

In [4]:
a

array([1., 2., 3.])

In [5]:
# все возможные типы данных, которые поддерживает numpy
np.sctypeDict

{'bool': numpy.bool,
 'float16': numpy.float16,
 'float32': numpy.float32,
 'float64': numpy.float64,
 'longdouble': numpy.longdouble,
 'complex64': numpy.complex64,
 'complex128': numpy.complex128,
 'clongdouble': numpy.clongdouble,
 'bytes_': numpy.bytes_,
 'str_': numpy.str_,
 'void': numpy.void,
 'object_': numpy.object_,
 'datetime64': numpy.datetime64,
 'timedelta64': numpy.timedelta64,
 'int8': numpy.int8,
 'byte': numpy.int8,
 'uint8': numpy.uint8,
 'ubyte': numpy.uint8,
 'int16': numpy.int16,
 'short': numpy.int16,
 'uint16': numpy.uint16,
 'ushort': numpy.uint16,
 'int32': numpy.int32,
 'intc': numpy.int32,
 'uint32': numpy.uint32,
 'uintc': numpy.uint32,
 'int64': numpy.int64,
 'long': numpy.int64,
 'uint64': numpy.uint64,
 'ulong': numpy.uint64,
 'longlong': numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'intp': numpy.int64,
 'uintp': numpy.uint64,
 'double': numpy.float64,
 'cdouble': numpy.complex128,
 'single': numpy.float32,
 'csingle': numpy.complex64,
 'half': numpy.

In [6]:
a

array([1., 2., 3.])

In [7]:
# таким образом можно преобразовывать данные / массивы, создаётся копия
print(np.int8(16.999999999))
print(np.int8(a))

16
[1 2 3]


In [8]:
b = np.array([[1, 2], [3, 4], [5, 6]])

In [9]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [11]:
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [12]:
# к элементам можно обращаться так (равносильно c[1][0][1])
c[1, 0, 1]

np.int64(6)

In [13]:
c[1, 0, 1] == c[1][0][1]

np.True_

### Функции автозаполнения, создания матриц и числовых диапазонов.

In [14]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# np.empty(shape, ...)
# Возвращает новый массив заданного размера и типа данных, но без определённых значений.
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# np.eye(N, M=None, ...)
# Возвращает массив размером N*M с единичными диагональными элементами (остальные равны 0)
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
# np.identity(n, ...)
# Возвращает квадратный массив с единичными диагональными элементами (остальные равны 0)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# np.zeros(shape, ...)
# Возвращает массив заданного размера и типа, состоящего из всех нулей
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
# np.ones(shape, ...)
# Возвращает массив заданного размера и типа, состоящего из всех единиц
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
# np.full(shape, value, ...)
# Возвращает массив заданного размера и типа со значениями value.
np.full((2, 3), 11)

array([[11, 11, 11],
       [11, 11, 11]])

In [71]:
# np.asmatrix("str")
# создаёт матрицу из строки
np.asmatrix("1 2 3 4")
# np.asmatrix("1 2 3 4") == np.asmatrix("1, 2, 3, 4")

matrix([[1, 2, 3, 4]])

In [78]:
# через ; можно создавать двумерную матрицу
np.asmatrix("1 2 3; 4 5 6")
# np.asmatrix("1 2 3; 4 5 6") == np.mat([(1, 2, 3), (4, 5, 6)])
# np.asmatrix("1 2 3; 4 5 6") == np.asmatrix([(1, 2, 3), (4, 5, 6)])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [79]:
# np.diag([a, b, c])
# создает матрицу, где на главной диагонали будут элементы a, b, c
np.diag([1, 2, 5])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 5]])

In [80]:
# Если в np.diag передать двумерный список или массив
# то эта функция выделяет элементы, стоящие на главной диагонали
np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([1, 5, 9])

In [ ]:
# np.tri(shape)
# создаёт матрицу размером shape где все элементы на главной диагонали и под ней - единицы
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [89]:
np.tri(4, 2)

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Если в np.tril передать массив, то обнулятся все элементы над главной диагональю
a = np.arange(9).reshape(3, 3)

In [84]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
np.tril(a)

array([[0, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [91]:
# Обратно работает np.triu
np.triu(np.arange(9).reshape(3, 3))

array([[0, 1, 2],
       [0, 4, 5],
       [0, 0, 8]])

Название | Описание
--- | ---
arange() | Возвращает одномерный массив с равномерно разнесёнными числами указанного диапазаона.
linspace(start, stop, ...) | Возвращает одномерный массив с равномерно разнесёнными числами, используя только значения начала и конца интервала.
logspace(start, stop, ...) | Возвращает одномерный массив с числами, равномерно распределённых по логарифмической шкале.
geomspace(start, stop, ...) | Формирование чисел по геометрической прогрессии.
meshgrid(x1, ..., xn, ...) | x1, ..., xn - одномерные последовательности или массивы, используемые для формирования координатной сетки по каждой из осей.
mgrid[] | Возвращает массив плотных координатных сеток.
ogrid[] | Возвращает открытую сетку значений.

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [102]:
# Можно указывать вещественные значения и константы
np.arange(1, 5, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
# np.linspace
# при указании в качестве количества значений
# 1 - получим только начало диапазона
# 2 - начало и конец
# 3 - начало, конец и среднее арифметическое
# и т. д.
for i in range(1, 5):
    print(np.linspace(0, np.pi, i))

[0.]
[0.         3.14159265]
[0.         1.57079633 3.14159265]
[0.         1.04719755 2.0943951  3.14159265]


In [ ]:
# np.logspace - логарифмическая шкала
for i in range(1, 5):
    print(np.logspace(0, 3, i))


[1.]
[   1. 1000.]
[   1.          31.6227766 1000.       ]
[   1.   10.  100. 1000.]


In [ ]:
# np.geomspace геометрическая прогрессия
np.geomspace(1, 16, 5)

array([ 1.,  2.,  4.,  8., 16.])

Фнукции формирования массивов на основе данных
Название | Описание
--- | ---
array(object, ...) | Преобразует список или кортеж object в массив NumPy.
asanyarray(list, ...) | Преобразует список list в массив array, сохраняя тип подкласса.
ascontiguousarray(list, ...) | Возвращает непрерывный массив в памяти, подобно как это организовано в языке C.
asmatrix(list, ...) | Преобразует входную последовательность list в матрицу NumPy (тип matrix).
copy(list, ...) | Возвращает копию массива list (если это объект Numpy) или просто создаёт массив на основе списка языка Python.
frombuffer(buffer, ...) | Преобразует данные из буфера в массив NumPy.
fromfile(file, ...) | Возвращает массив из данных текстового или бинарного файла file.
fromfunction(func, shape, ...) | Создаёт массив размерностью shape с помощью функции func.
fromiter(iter, ...) | Создаёт массив на основе итерируемого объекта.
fromstring(string, ...) | Создаёт массив из данных строки.
loadtxt(file, ...) | Формирует массив из данных текстового файла.

In [130]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [131]:
b = a

In [134]:
b[0][1] = 100

In [137]:
a

[[1, 100], [3, 4]]

In [138]:
c = np.copy(a)

In [ ]:
c[0][1] = - 1000
print(c, a, sep='\n')

[[    1 -1000]
 [    3     4]]
[[1, 100], [3, 4]]
